language: android
dist: trusty
android:
    components:
        - tools
        - platform-tools
        - build-tools-30.0.2
        - android-30
    licenses:
        - android-sdk-.+
        - google-sdk-.+