language: android
os: linux
dist: trusty
jdk:
  - oraclejdk8

notifications:
  email: false

env:
 global:
 - ANDROID_API=30
 - ANDROID_BUILD_TOOLS=30.0.3

android:
  components:
  - tools
  - tools # Running this twice get's the latest build tools (https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI)
  - platform-tools
  - build-tools-${ANDROID_BUILD_TOOLS}
  - android-${ANDROID_API}

before_install:
  - echo yes | sdkmanager "platforms;android-${ANDROID_API}"

script:
  - "./gradlew clean test build"

